apiVersion: apps/v1
kind: Deployment
metadata:
  name: delete-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delete-pod
  template:
    metadata:
      labels:
        app: delete-pod
    spec:
      containers:
        - name: delete-pod
          image: azimiali/server-delete:latest
          # You can also use IfNotPresent but it might lead to old images
          imagePullPolicy: "Always"
          env:
            - name: DATABASE_URI
              value: mongodb+srv://alibabaazimi:tSqT8sll6hMta6Hp@cc-exercise.2nboky2.mongodb.net/?retryWrites=true&w=majority&appName=cc-exercise
          ports:
            - containerPort: 3030